# Training configuration for IR modality

data_path: data/
epochs: 50
batch_size: 16
learning_rate: 0.0002
pretrained: models/resnet/resnet50_ir.pth  # or null if training from scratch
save_dir: results/logs/ir/
num_classes: 1
